# Generated by Django 2.2.15 on 2020-09-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(default='Empty', upload_to=''),
            preserve_default=False,
        ),
    ]
