# Generated by Django 2.2.15 on 2020-09-03 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_designation',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_organization',
        ),
    ]
